# This is a weird way of telling Travis to use the fast container-based test
# runner instead of the slow VM-based runner.
sudo: false

language: go

# Only the last two Go releases are supported by the Go team with security
# updates. Any older versions be considered deprecated. Don't bother testing
# with them.
go:
  - 1.10.x
  - 1.9.x

# Only clone the most recent commit.
git:
  depth: 1

install: true

# Don't email me the results of the test runs.
notifications:
  email: false

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

before_script:
  - dep ensure

script:
  - make test